version: '3.8'

services:
  auth-service:
    build: . # Путь к каталогу с вашим сервисом аутентификации
    ports:
      - "5000:5000"
    environment:
      - CONFIG=./config.json
      - DB_NAME=auth_db
      - DB_USER=auth_client
      - DB_PASS=auth_client
      - DB_ADDR=postgres:5432
      - CACHE_ADDR=redis:6379
      - CACHE_DB=0
    depends_on:
      - postgres
      - redis

  postgres:
    build: ./db
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=auth_client
      - POSTGRES_PASSWORD=auth_client
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  goose:
    build: ./db/migrations
    environment:
      - DB_NAME=auth_db
      - DB_USER=auth_client
      - DB_PASS=auth_client
      - DB_ADDR=postgres:5432
      - DB_SSL=false
      - GOOSE_DRIVER=postgres
      - GOOSE_URL=postgresql://auth_client:auth_client@postgres:5432/auth_db?sslmode=disable
    depends_on:
      - postgres
    

volumes:
  pgdata:
